# LastFM for Ubersicht
# Patrick Pan, patrick.pan@patrickpan.com

# Replace "your_username_here" with your username (leave the quotes)
# If you're being told to enter your username even though you already have:
# 1) You haven't scrobbled before (probably not)
# 2) Last.FM changed their API. Email me and mention Last.FM in the subject line!

command: 'username=' + 'alex_foley' + '; curl -s "http://ws.audioscrobbler.com/2.0/?method=user.getRecentTracks&user=$username&api_key=b25b959554ed76058ac220b7b2e0a026&format=json&limit=1"'

refreshFrequency: 5000

render: (output) ->
  # this is a bit of a hack until jQuery UI is included natively
  $.getScript("https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js", () ->
    $('#lastfm').draggable()
    return
  )
  # apologize for the DOM vomit here
  '<div id="lastfm" class=""><span id="track">Track</span> - <span id="artist">artist</span> <span id="timestamp"></span></div>'

afterRender: ->

update: (output) ->
  if(!output)
    return
  data = JSON.parse(output)
  if(!data.recenttracks)
    $('#track').text 'Please enter your Last.FM username in lastfm.coffee!'
    return
  track = data.recenttracks.track[0]
  if $('#track').text() != track.name
    $('#track').text track.name
    $('#artist').text track.artist['#text']
    if track['@attr']
      $('#timestamp').text ''
      $('#lastfm').removeClass('hidden')
    else
      $('#timestamp').text @timeString(new Date / 1000 - (track.date.uts))
      $('#lastfm').addClass('hidden')
		return
	
#		if $('#timestamp').text() == ''
#    	$('#lastfm').show
#  	else
#    	$('#lastfm').hide
#  	return



style: """
bottom: -2px
left: 2px
color: rgba(255, 255, 255, 0.6)
font-size: 14px
font-family: Helvetica Neue, Georgia
font-style: italic
width: 500px
height: 20px

#lastfm
  position: absolute

#artist, #timestamp
  font-weight: 300
 

#track
  font-weight: 300
	
.hidden
	visibility: hidden
"""

timeString: (time) ->
  if time < 60
    return 'Now Playing'
  if (time /= 60) < 1.5
    return 'A minute ago'
  if time < 59.5
    return Math.round(time, 0) + ' minutes ago'
  if (time /= 60) < 1.5
    return 'An hour ago'
  if time < 23.5
    return Math.round(time, 0) + ' hours ago'
  if (time /= 24) < 1.5
    return 'An hour ago'
  if time < 29.5
    return Math.round(time, 0) + ' days ago'
  if (time /= 30) < 1.5
    return 'A month ago'
  if time < 11.5
    return Math.round(time, 0) + ' months ago'
  return 'A long, long time ago'


# ---
# generated by js2coffee 2.1.0
